### ISSUE TITLE
Requirements management

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#1]
Check this file [here](https://github.com/netcriptus/skyscanner_scrapper/blob/master/requirements.txt).

The usual way to manage requirements on a python project is using a file named `requirements.txt`, like the one linked above. This way, it's possible to run a command like:

`pip install -r requirements.txt`

This way you can be sure it will use the right lib versions, and will not eventually run on lib incompatibilities and deprecations.

Can you please include one of these on the project?

**Comment by rudolfce** [comment]
:+1:  sweet! Thanks!
