### ISSUE TITLE
Project broken

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#10]
Some dork recently broke the project on a pull request. This wouldn't happen if the project had some automated tests! Please, implement them!

Some useful reading:
[nosetests](https://nose2.readthedocs.org/en/latest/) - for actually running the tests
[unittest](https://docs.python.org/3/library/unittest.html) - writing the tests
[mock](https://docs.python.org/dev/library/unittest.mock.html) - simulates some calls and responses
[factory_boy](https://factoryboy.readthedocs.org/en/latest/) - create fixtures for your database
[lettuce](http://lettuce.it/tutorial/simple.html) - for behaviour test, probably too much for now.
[Some examples](https://github.com/netcriptus/EF_scraper/tree/master/scraper/tests)

**Comment by rudolfce** [comment]
And it's fixed. I'll leave the issue open, since there is a bigger topic on it.

**Comment by rudolfce** [comment]
Just added a test folder with some test routines that nosetests can find. I will dedicate some more love to it later, but I think it already works as a first attempt to prevent from broken merges.

**Comment by netcriptus** [comment]
Almost there. Check the comments on your last commit. Fix it, then let's talk about the next steps.

**Comment by rudolfce** [comment]
And done. I hope no panda got hurt because of me this time.

**Comment by netcriptus** [comment]
Great! Close this issue, create a pull request from develop to master now that you have a truly stable version!

**Comment by rudolfce** [comment]
:+1:
