### ISSUE TITLE
Scale up

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#11]
OMG! The twitter scraper is a _HUGE_ success! But the current app is not handling it very well, we have hundreds of thousands of bazillions requests per nanosecond! Also, we have to use different configurations for different countries. Configuration itself does not justify using a different app!

We have no choice but to make multiple instances of the same app and make the configuration an argument! Please, make it an [app factory](http://flask.pocoo.org/docs/0.10/patterns/appfactories/) now!

**Comment by rudolfce** [comment]
:+1:

**Comment by rudolfce** [comment]
It required some care because of the circular imports, but it's working now.
