### ISSUE TITLE
Scale up(per)

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#13]
We're a huge success, even more than we ever dreamed! I've heard even twitter is using your scrapper now!

But the app is not holding! We need to make it more scalable, so please:
1. Let's make it into an API only. Stop rendering pages, no more fancy html, no more fancy interface. You get a request, you return a response, either in JSON, or just a status code (depending on the case).
2. Replace the function that does the scrapping itself by a [worker](http://docs.celeryproject.org/en/latest/userguide/workers.html). The new flow should look like this:
   - When you get a request, check the database. If this user is there, return the info as JSON, with the **proper http status code**
   - If the user is not there, spawn a celery worker to fetch the info asynchronously and put it in the database. Return nothing but the **proper http status code** for this request.

Some really useful links:

[HTTP Status Codes](https://httpstatuses.com/)
[Celery workers documentation](http://docs.celeryproject.org/en/latest/userguide/workers.html)
[Celery worker working example](https://github.com/netcriptus/EF_scraper/blob/master/scraper/facebook/controllers.py) -- Only click here when you have something implemented yourself (working or not, just give it a try first). This link gives away the answer to the proper http codes and how the celery should be implemented, so half the fun dies here.
## ATTENTION

This is **the last assignment** for this training exercise! So:
1. Give your best.
2. Break this in as many subtasks as you see fit.
3. Merge the changes **only in the development branch!** Keep the master branch untouched from here on.
4. Make Pull Requests from the branches you create to the Development Branch. And most important, **wait for Code Review**! A PR is worth nothing if your code is not reviewed! You can use this thread to ask for a review (please remember to leave a link to the PR).
5. Don't panic! You don't have to do it all by yourself, this thing gets a bit nasty in this stage. Ask for help whenever needed.

Congratulations, you've done really well so far. Best of luck!

May the force be with you!

**Comment by rudolfce** [comment]
:+1: 

Nice!

**Comment by rudolfce** [comment]
Back to the land of the living.
And that's a pull request. Unittesting is compromised, so I'm doing some changes to fix that. I would like some opinions either way.

https://github.com/rudolfce/scrapper/pull/14

**Comment by netcriptus** [comment]
Just a few tweaks left. You're really close.
