### ISSUE TITLE
manage.py file

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#2]
Check this file [here](https://github.com/netcriptus/skyscanner_scrapper/blob/master/manage.py).

Flask (and sometimes django) projects like to use a `manage.py` file. There you can add some useful custom commands (like those you see on the example linked above) but you also get some cool standard commands for free, like:

`./manage.py runserver`

It would be pretty nice to have this here.

**Comment by rudolfce** [comment]
:+1:  will look into it
