### ISSUE TITLE
Py3k

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#3]
Python 2 is soooo 2015... Why not update the project and use python 3? I mean, every dependency you're using in the project is already widely supported. I can see no reason to doom this awesome api to the past.

**Comment by rudolfce** [comment]
That's actually funny, cuz I just tried it on Pyhon 3.4 out of the box and it worked. Looks like I was still on the land of similarity between them. I'll update the README to match this, and will go on considering python 3 as my goal. Thanks for the heads up!
