### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#4]
It would be an excellent idea not to query and not to parse twitter every single time... maybe we could include the already parsed names on a database? You know, using models in [SQLAlchemy](http://www.sqlalchemy.org/)?

**Comment by rudolfce** [comment]
:+1:

**Comment by rudolfce** [comment]
It surely could get some more love, but it's already working. I hope to improve the database functionality with some time and development. SQLAlchemy was really nice to learn, thanks for the tip!
