### ISSUE TITLE
Bug with big profiles

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#6]
When inserting big profiles on the scraper, it breaks. Try to scrape `azaghal` for instance, you'll get a 500.

**Comment by rudolfce** [comment]
Hello! It was a 'mostly' known issue with unicode characters that I had not given attention to. It happens on Python2 in the return line of the mine_user function. I've put there a str conversion, and that freaks out when dealing with 2 byte chars. On Python 3 that did not happen for me, only on Python 2.

So, the conclusion was that his humble house in Khazad-dûm was generating issues. It should be solved by now. Let me know if it's not. For now, let's not ask him to move.
