### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/scrapper#8]
It's good that things are a bit more advanced now. It's now time to review the project structure, maybe follow some pattern for this kind of project. Have a look [here](https://github.com/netcriptus/skyscanner_scrapper) and get inspired (by inspired I mean follow this organization for your files).

Don't look the code quite yet, only file structure.

**Comment by rudolfce** [comment]
:+1:

**Comment by rudolfce** [comment]
Oh, I closed the issue, but forgot to comment. I'm migrating to the gitflow workflow now. I did this change in the development branch. Once database stuff is dandy, I'll merge it into the master branch. Thanks for the tip.

**Comment by netcriptus** [comment]
I would reopen this issue.

There's still one folder named `db_stuff`. Things related to database are either models or configurations. Check [this](https://github.com/netcriptus/EF_scraper/tree/master/scraper) project. Use the ~~force~~ MVC. There's no MVDBstuffC.

Remember to build your project expecting growth. Prepare for changes you cannot predict.

**Comment by rudolfce** [comment]
Reopened it for discussion. Made some changes on the structure.

**Comment by netcriptus** [comment]
We're closer, but not there yet.
- [x] You don't need a json config file. Use python. Define python `CONSTANTS` (constants are always caps) and use them. Parsing json is slow, you don't wanna do that everytime your app goes up.
- [x] The db commands should all be in the `manage.py` file. There should not exist a `management.py` file inside the models folder.
- [x] There are files inside the models folder that are not models. Remember model is database-related business logic, and you are actually doing data related operations in some files (including data fetch and parse). Please [watch this](https://www.youtube.com/watch?v=ku3QkWcPSEw&list=PL483BC6180885896B) (the whole playlist).
- [x] The model file usually takes the name of the model (or group of models) it is defining. Unless the folder itself took this name already (not your case, this is usually done on larger projects).
- [x] Move all app-related stuff to a `scraper` folder. Keep the root clean and organized.

**Comment by rudolfce** [comment]
I come from a C background, so "hardcoding" (eventhough Python doesn't make it that _hard_) is strange for me yet. But let's get to it.

**Comment by netcriptus** [comment]
> "hardcoding" [...] is strange for me yet

Don't worry, we'll get to it.

**Comment by netcriptus** [comment]
Now just make the `controller` folder in plural `controllers` and you can close this issue.
